### ISSUE TITLE
Refs should be forwarded to the RJSF Form component

### ISSUE THREAD

**Issue by e-cooper** [ivarprudnikov/rjsf-conditionals#140]
Right now, any ref supplied to the result from `applyRules` will point to the wrapped component instead of the underlying `Form` from RJSF. This prevents the ability to [submit the form programmatically](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/internals/#submit-form-programmatically). To fix this, the library should be using [`React.forwardRef`](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components).

**Comment by ivarprudnikov** [comment]
Thanks!

* Followed the docs in [Forwarding refs in higher-order components](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components)
* Added a test case in [applyRules.test.js](https://github.com/ivarprudnikov/rjsf-conditionals/blob/master/test/applyRules.test.js#L131)
* Had to split out `FormWithConditionals` from within `applyRules(...)` to make it testable after using `React.forwardRef`

**Comment by ivarprudnikov** [comment]
v1.1.0 was released 
Notes - https://github.com/ivarprudnikov/rjsf-conditionals/releases/tag/v1.1.0
NPM - https://www.npmjs.com/package/rjsf-conditionals
