### ISSUE TITLE
PropTypes warning when using 

### ISSUE THREAD

**Issue by howientc** [ivarprudnikov/rjsf-conditionals#246]
**Describe the bug**
Warning: Failed prop type: Invalid prop `formComponent` supplied to `FormWithConditionals`.
    in FormWithConditionals (created by ForwardRef)

 - Provide steps to reproduce: 
 - 
 `import Form from '@rjsf/material-ui';`
instead of:
 `import Form from '@rjsf/core';`

Note that in the source for MuiForm, it declares the type of the form as:
`declare const MuiForm: React.ComponentClass<FormProps<any>> | StatelessComponent<FormProps<any>>;`
which is not compatible with PropTypes check in rjsf-conditionals

**Expected behavior**
rjsf-conditionals should support other UI flavors without warning.

**Library details:**
 - Version number: 1.1.2
 - Also using 
 - @rjsf/core": "^2.4.1",
 - @rjsf/material-ui": "^2.4.1",
  
 - Which file/dependency is used, which module system? es6

**Additional context**
I believe the error is benign.

**Comment by aucuparia** [comment]
Also happens with `import Form from '@rjsf/bootstrap-4'`.

**Comment by ivarprudnikov** [comment]
I do agree this is annoying (and only on dev env), but it looks harmless. I've added an explicit example to the playground to see if there are errors in "production" version https://ivarprudnikov.github.io/rjsf-conditionals/sum-material-template.html

Please could you also suggest how to fix it, or create a PR?

**Comment by aucuparia** [comment]
I have no suggestions on how to fix it. Currently I'm assuming it's a benign error (and haven't found it to be otherwise yet). Thanks for the speedy response.
