### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime-corejs2/core-js/array/is-array

### ISSUE THREAD

**Issue by Aditi-1400** [ivarprudnikov/rjsf-conditionals#301]
**Describe the bug**
Hey, thanks for the amazing library, but I am trying to use and am getting this error:
`Module not found: Can't resolve '@babel/runtime-corejs2/core-js/array/is-array`

**To Reproduce:**
 I am using the same code as specified in [Page Sum](https://github.com/ivarprudnikov/rjsf-conditionals/tree/master/playground/page-sum)

**Library details:**
 - "@rjsf/core": "^3.0.0",
 - react-jsonschema-form-conditionals": "^0.3.15"
 - "react-scripts": "4.0.3"
 - "rjsf-conditionals": "^1.1.4",

**Desktop/Smartphone (please complete the following information):**
 - Device: [Macbook Air M1]
 - OS: [macOS]
 - Browser [Chrome]

**Comment by ivarprudnikov** [comment]
I did not test it with the `@rjsf/core v3` yet.

**Comment by ivarprudnikov** [comment]
I have released a `v1.1.5` that includes a couple of dependency updates. One of those is related to corejs `Bump @babel/runtime-corejs2 from 7.13.8 to 7.14.8`. Might be related.

**Comment by ivarprudnikov** [comment]
FYI `react-jsonschema-form-conditionals` is something that worked with @rjsf v1, current library (`rjsf-conditionals`) supersedes it.

**Comment by ivarprudnikov** [comment]
Please refer to the `playground/` setup that currently uses the `"@rjsf/core": "^3.1.0"`. Webpack config is in `
webpack.playground.prod.js`. Let me know if you're still having an issue.
