### ISSUE TITLE
does not work with anyOf, oneOf, allOf and such

### ISSUE THREAD

**Issue by Morriz** [ivarprudnikov/rjsf-conditionals#335]
**Describe the bug**
Your validation logic does not take into account anyOf, oneOf, allOf. It throws errors when it hits those.

**Expected behavior**
The validation to be performed without problems, and the lookup of the props to be successfully performed by using the utils provided by rjsf core.

**Library details:**
 - Version number: 1.2.0

**Comment by Morriz** [comment]
Sorry, if this does not say anything to you I can't help...we moved on since no support for these constructs seems to exist in rjsf-conditionals (I stepped through the code in the debugger and found none). If you do have a working example it would be beneficial to show them in the docs ;)

**Comment by ivarprudnikov** [comment]
It would be useful if there was a supported JSON schema version explicitly mentioned in the docs.
