### ISSUE TITLE
Support ASYNC extra actions

### ISSUE THREAD

**Issue by Maikel-Nait** [ivarprudnikov/rjsf-conditionals#342]
**Describe the bug**
Custom extraActions works great, as long as they are synchronous functions. Modifying schema or formData objects inside these synchtronous functions effectively updates the schema / formData fields.

The problem comes when trying to use **async** functions when executing extraActions.
Although async functions can be executed successfully, updating schema or formData objects do not have any effect.

For example, I have an async extraAction that performs an AJAX call and, based on the response, updates the formData object.
Even though the formData object is updated with the AJAX response, no changes are rendered on the form.

I believe the problem comes from the fact **rulesRunner**._doRunRules_ calls all the extraAction events in a synchronous way

`events.forEach((event) =>
      execute(event, schemaCopy, uiSchemaCopy, formDataCopy, extraActions)
 );`

If any of the "execute" calls is actually an async function , the xxxCopy parameters are updated when doRunRules have actually ended, and the update takes no effect.

Not sure if I'm exactly right about the root cause, but in any case, async extraActions do not work.
Is there any workaround for this, or an easy fix on the library that would allow this scenario to work ?

**Comment by ivarprudnikov** [comment]
What sort of a problem are you trying to solve? It is a bit unexpected to have a long running function because at a minimum extra actions should be able to mutate the whole schema in between keystrokes. You could wrap async functionality in a field similar to autocomplete and then change the schema when result comes back, this could be done through [custom fields](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/)

**Comment by Maikel-Nait** [comment]
I'm basically trying to code a typical example of dropdown dependencies :  i.e You choose a Country on one dropdown, and then a dependent City dropdown must be refreshed, only displaying cities of the country selected on the first dropdown. There could even be a third dependent dropdown, i.e sightseeing places, after choosing the city, the sightseeing dropdown must be updated as well.  Now there are different ways to achieve this with JSON schemas.   One approach is to use the "dependencies" JSON keyword to construct a "oneof" dependency tree... as I managed to demo on this code sample here: 

https://codesandbox.io/s/fervent-cherry-lokjk?file=/src/App.js

but this makes the JSON schemas kind of complicated, when you have many related dropdowns, and you have to build the entire schema with all the values beforehand.

So I was thinking of using JSON conditionals, to build rules that, given a value on one Select dropdown, would ajax-load the corresponding values of a dependent dropdown (at least the very first time, the response could be cached, so that we don't need to make the ajax call everytime we choose the same value).  This is when I realized the rule engine does not actually support async rules.

Right now I'm solving the problem by "preloading" all the dropdown values I need in different arrays, and then switching between them when needed. (the rule updates the "enum" property of a select input from one of the arrays). This approach works fine so far. But of course I have to preload all the possible values of all the dropdowns.  For small data sets,  this is not a problem.  But if you have to preload hundreds of options before the schema can be rendered... that starts to become a problem.

**Comment by ivarprudnikov** [comment]
It seems to be a great feature, unfortunately the module is in a maintenance mode. Furthermore is is not a small feat to refactor code and allow for async execution. I'll keep the issue open for anyone willing to open up a PR with proposed changes to allow async.

**Comment by Maikel-Nait** [comment]
Agree.  I did some quick coding, trying to add async capability to the library, but failed miserably.  It's more complicated than expected. Still, as you mention, it would be awesome.

**Comment by ivarprudnikov** [comment]
I'll close this due to the inactivity. I have no time to spare here.
