### ISSUE TITLE
Switch @babel/runtime-corejs2 to @babel/runtime-corejs3

### ISSUE THREAD

**Issue by OleksiL** [ivarprudnikov/rjsf-conditionals#370]
Could you upgrade @babel/runtime-corejs2 dependency to the latest @babel/runtime-corejs3.

P.S. Thank you for your work and efforts. Had to switch from old react-jsonschema-form to rjsf/core and your fork was simplified it for me.

**Comment by ivarprudnikov** [comment]
Would you mind doing a PR? I would consider it a breaking change BTW
