### ISSUE TITLE
require action with condition not working

### ISSUE THREAD

**Issue by Zonxpk** [ivarprudnikov/rjsf-conditionals#477]
**Describe the bug**
I used require event with condition like 
```
[{
    "conditions": {
        "lat": {
            "not": "empty"
        }
    },
    "event": {
        "type": "require",
        "params": {
            "field": "lng"
        }
    }
}]
```

Then got error when formData have value of `lat` field

<img width="400" alt="image" src="https://user-images.githubusercontent.com/50532697/216230433-480668c7-cd2d-418f-b2db-e055976fc0d3.png">

Not sure why.

**Library details:**
 - "rjsf-conditionals": "^1.5.0",

**Comment by ivarprudnikov** [comment]
Cannot reproduce as there is no schema, uiSchema, model json values that would lead to this. Please reopen with more info if you can.
