### ISSUE TITLE
Support for react 17?

### ISSUE THREAD

**Issue by Fronix** [ivarprudnikov/rjsf-conditionals#482]
Any way to up the peer dependancy to support React 17? Since RJSF already does support it seems odd this doesn't.

**Comment by ivarprudnikov** [comment]
Would you mind making a PR? I'm not actively maintaining this library.

**Comment by Fronix** [comment]
> Would you mind making a PR? I'm not actively maintaining this library.

Sorry, I forgot to close this issue, I ended up using another solution since this library isn't maintained as you said.

**Comment by NishantChorge7** [comment]
> > Would you mind making a PR? I'm not actively maintaining this library.
> 
> Sorry, I forgot to close this issue, I ended up using another solution since this library isn't maintained as you said.

May I know which library are you using?

**Comment by Fronix** [comment]
> > > Would you mind making a PR? I'm not actively maintaining this library.
> > 
> > 
> > Sorry, I forgot to close this issue, I ended up using another solution since this library isn't maintained as you said.
> 
> May I know which library are you using?

Ended up writing a custom solution
