### ISSUE TITLE
Rules code clarification

### ISSUE THREAD

**Issue by emilian** [ivarprudnikov/rjsf-conditionals#511]
Hi,

Let's say a rule removes a field from the UI based on a condition. When that condition is no longer satisfied, how does the library know to append the field that was previously removed?

Hope it makes sense.

**Comment by ivarprudnikov** [comment]
> how does the library know to append the field that was previously removed?

Component watches the inputs and recalculates the state after the changes were detected. It does not append separate fields but re-renders the form according to the rules.
